CREATE TABLE organigrama (
    ID_ORGANIGRAMA int(11) NOT NULL AUTO_INCREMENT,
    AREA varchar(60) NOT NULL,
    DESCRIPCION text NOT NULL,
    AREA_DEPENDE text NOT NULL,
    NIVEL int(11) NOT NULL,
    TIPO_AREA int(11) NOT NULL,
    TITULAR varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

SET FOREIGN_KEY_CHECKS = 0;
SET GLOBAL FOREIGN_KEY_CHECKS = 0;